AllCops:
 SuggestExtensions:
    rubocop-rspec: true
    rubocop-rails: false
 NewCops: enable
 Exclude:
    - 'db/schema.rb'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/BlockLength:
  Max: 40
  
Metrics/MethodLength:
  Max: 40
  
Metrics/AbcSize:
  Max: 40
